version: '3'

services:
    database:
        container_name: postgres-master
        image: "postgres:11.9" 
        env_file:
            - database.env
        volumes:
            - data-master:/var/lib/postgresql/data
            - ./replication-entrypoint.sh:/replication-entrypoint.sh
        command: bash -c '/replication-entrypoint.sh && docker-entrypoint.sh postgres'

volumes:
    data-master:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/libo/git/liboch/main/playground/docker/07_postgres_docker/data-master
  
##  slave-data:
##    driver: local
##    driver_opts:
##      o: bind
##      type: none
##      device: /home/libo/git/liboch/main/playground/python/07_postgres_docker/slave-data
##
