version: '3'

services:
    database:
        container_name: postgres-master
        image: "postgres:11.9" 
        user:
            1000:1000
        env_file:
            - database.env
        volumes:
            - data-master:/var/lib/postgresql/data
            - ./replication-entrypoint.sh:/replication-entrypoint.sh
            - /etc/passwd:/etc/passwd:ro
#command: bash -c '/replication-entrypoint.sh && docker-entrypoint.sh postgres'
        command: bash -c 'sleep 1000'
        ports: 
            - 5432:5432

volumes:
    data-master:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: /home/libo/git/liboch/main/playground/docker/07_postgres_docker/data-master
  
##  slave-data:
##    driver: local
##    driver_opts:
##      o: bind
##      type: none
##      device: /home/libo/git/liboch/main/playground/python/07_postgres_docker/slave-data
##
