---
- hosts: all 
  user: root
  tasks:
      - name: Setup | add line to authorized hosts
        lineinfile:
            path: /root/.ssh/authorized_keys
            line: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJXRaWtZtjzcRst9cbDb+ALmdr3XwQZ3ypeKp4PDsTpQTUZ97zjMTec03KaFGoST1Sfmd5iojUsXEg4krVqoBRIEQX519PsVXWpDg6pl3d9zMLv7oF9mRbCD9+GRS6oCE4L1YBAfJyYDhJWTAFWAsoNgSXgnoFSVhXz81dP+Bg/KNl0zBeZICvxoSMVDzxpKCa1ga2gugIG2J+KwxBbYygfs5QeYnMbO6X8m0uCqF8yhI4PFm/Jdsnq040JZCeiuXT4X8il8LYrkKC3LRpR5Vn//GDfG+uIXU2j44jAkhjcVTMLUvmfEf/W1H4aJwPXSriXakLVTCbk4qr4LQ3Utm9 libo@oblivion'
      - name: Setup | add private key
        copy:
            src: /home/libo/git/liboch/main/playground/linuxAcademy/ssh/id_rsa
            dest: /root/.ssh/id_rsa
            owner: root
            group: root
            mode: '0600'
      - name: Setup | add config
        copy:
            src: /home/libo/git/liboch/main/playground/linuxAcademy/ssh/config
            dest: /root/.ssh/config
            owner: root
            group: root
            mode: '0600'

